# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rehan Butt
email: me@rehanbutt.com
year: 2025
site-title: 2025 Year in Review
description: > # this means to ignore newlines until "baseurl:"
  As we bid farewell to 2024, let's review the year and the path it carved. I spoke at a conference and earned my second film credit. I took part in several industry events, enhancing existing skills and learning new ones. Put together a "Making Of" for my year in review series, shipped some awesome new software products and took some amazing photos during my travels.

baseurl: "" # the subpath of your site, e.g. /blog
mainurl: "https://rehanbutt.com"
url: "https://2025.rehanbutt.com" # the base hostname & protocol for your site
keywords: >
  year in review,2025,yearly recap,devzgn,devzgner,personal review, personal recap,recap 2025,Design,UX,UI,webdev,branding,portfolio,site

# Build settings
markdown: kramdown

plugins: [jekyll-sitemap]

collections:
  songs:
    output: false
  events:
    output: false
  fave-things:
    output: false
  travel:
    output: false